apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-java-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi

                   
