apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-java-pv
  namespace: dev
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/mnt/java-data"

